## docker compose -f mysql-local.yaml up
version: '3.8'
services:
  database:
    image: arm64v8/mysql:oracle
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'   
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'      
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - '~/docker/mysql-data:/var/lib/mysql'